database:
  dialect: mysql
  driver: mysqlconnector
  host: localhost
  port: 3306
  db_name: mybar_blog
  user: mybar
  password: mybar835
  minsize: 1
  maxsize: 10
  charset: utf8

host: 127.0.0.1
port: 8080